export const barrios = [
  {
    location_id: 25960,
    location_name: "CLUB DE CAMPO EL NACIONAL",
    nombre: "El Nacional",
    ubicacion: "General Rodríguez",
    acceso: "",
    caracteristicas_generales:
      "365 hectáreas, 906 lotes, promedio de 1350 m2 por lote, entorno natural privilegiado, microclima particular.",
    infraestructura_deportiva: [
      "Campo de Golf",
      "Tenis",
      "Fútbol",
      "Cabalgatas",
      "Equitación y Salto",
      "Lago para deportes náuticos sin motor",
      "Piscina",
      "Gimnasio",
      "Spa",
    ],
    infraestructura_servicios: [
      "3 Club House",
      "Red cloacal",
      "Electricidad y gas",
      "Telefonía e internet",
      "Avenidas colectoras",
      "Sistema de seguridad permanente de última generación",
      "Plan permanente de forestación",
      "Huerta orgánica y tambo",
      "Área para colegio, jardín maternal y campo deportivo",
    ],
    lotes:
      "Entre 1.000 y 1.900 m2, con un promedio de 1.350 m2. Frentes amplios con mínimos de 25 metros.",
  },
  {
    location_id: 26240,
    location_name: "CLUB DE CAMPO SAN DIEGO",
    nombre: "San Diego",
    ubicacion:
      "Margen derecha de la colectora Norte del Acceso Oeste, a la altura del kilómetro 41.5, Moreno.",
    acceso:
      "Directo desde la colectora a través de un puente e ingreso secundario sobre la ruta 25.",
    caracteristicas_generales:
      "1158 lotes, entre 1500 y 2750 metros cuadrados cada uno, 410 hectáreas totales (50% áreas comunes y 50% áreas privadas),  arboleda añosa, entorno natural, fauna autóctona, arroyos de agua dulce y lagunas.",
    infraestructura_deportiva: [
      "7 canchas de fútbol",
      "Polideportivo cubierto",
      "Gimnasio",
      "Spa",
      "6 canchas profesionales de polo",
      "1 cancha de golf de 18 hoyos",
      "1 cancha de golf de 9 hoyos",
      "Driving de práctica",
      "22 canchas de tenis de polvo de ladrillo",
      "4 canchas de tenis de cemento",
      "4 canchas de paddle",
      "Piscina descubierta",
      "Piscina cubierta climatizada",
      "Recreación para niños y adolescentes",
      "Teatro y actividades culturales",
    ],
    infraestructura_servicios: [
      "Consultorio médico con ambulancia y reanimación cardíaca 24 hs",
      "4 restaurantes",
      "Centro comercial",
      "Electricidad, gas y tendido de red de cloacas y agua en construcción",
      "Iglesia católica",
      "Cerco perimetral eléctrico y guardia las 24 hs con vigilancia con monitoreo on-line",
    ],
    lotes:
      "1158 lotes de 1500 a 2750 metros cuadrados. 63 unidades en PH tipo dúplex o dormies con vista al golf o al house principal.",
  },
  {
    location_id: 26229,
    location_name: "BANCO PROVINCIA",
    nombre: "Banco Provincia",
    ubicacion:
      "Francisco Alvarez (kilómetro 44,5), Moreno. Acceso por calle Gorriti.",
    acceso:
      "Calle Gorriti totalmente pavimentada e iluminada, con garita de vigilancia las 24 horas a la bajada de la autopista.",
    caracteristicas_generales: "",
    infraestructura_deportiva: [
      "Golf (9 hoyos par 3)",
      "14 canchas de tenis (11 de polvo de ladrillo y 3 de cemento)",
      "4 canchas de fútbol reglamentarias (3 con iluminación artificial y tribunas)",
      "2 canchas de fútbol para entrenamiento",
      "1 cancha de hockey reglamentaria de césped sintético iluminada",
      "2 canchas de pelota paleta",
      "2 Playones multideportivos",
      "2 frontones",
      "2 canchas de básquet con iluminación artificial",
      "1 cancha de vóley con iluminación artificial",
      "1 cancha de vóley de arena",
      "6 canchas de pádel (4 con iluminación artificial)",
    ],
    infraestructura_servicios: [
      "Club House Principal de 400 m2 con restaurante",
      "Sector de parrillas y bosque arbolado",
      "Quincho para espacio cultural con equipo central frío-calor",
      "Sala de juegos y reuniones",
      "Sector con juegos infantiles",
      "Biblioteca",
      "Oratorio",
      "Servicio de Emergencias Médicas las 24 hs. los 365 días del año",
      "Servicio de seguridad electrónica (cerco, cámaras, alarmas y alarmas domiciliarias)",
      "Servicio de Seguridad física las 24 hs. los 365 días del año",
      "Cajero Automático Bapro Link las 24 hs.",
      "Sistema Provincia Net",
      "Gas Natural",
      "Suministro Eléctrico Domiciliario",
      "Telefonía particular",
      "Internet por banda ancha",
    ],
    lotes: "",
  },
  {
    location_id: 26231,
    location_name: "CAMPOS DE ALVAREZ",
    nombre: "Campos de Alvarez",
    ubicacion:
      "Francisco Álvarez, Km 41 de la Autopista del Oeste, salida Reja Grande, Moreno.",
    acceso:
      "A 300 metros de la Autopista del Oeste. Acceso también desde la Ruta 5 km 42. A 1,9 km de la estación de Francisco Álvarez del FFCC Sarmiento y con línea de colectivo 501 ramal 38.",
    caracteristicas_generales:
      '467 lotes en total, 453 viviendas construidas, 65 hectáreas, 51.000mts² de espacios comunes. Lotes amplios con mucho verde: desde 900 a 1200 m2, con frentes espaciosos. Calles tipo "cul de sac".',
    infraestructura_deportiva: [
      "2 piletas de natación",
      "4 canchas de tenis",
      "Cancha de fútbol 5",
      "Cancha de fútbol 11",
      "Cancha de vóley",
      "Playón con aro de básquet",
      "Gimnasio con aparatos",
      "Colonias de verano e invierno para menores",
      "Coordinación deportiva con amplia gama de actividades",
    ],
    infraestructura_servicios: [
      "Club House con Wifi",
      "Sauna",
      "SUM",
      "Restaurante con delivery",
      "Internet (Telecentro, Telered y Telefónica)",
      "TV por cable y HD (Telered)",
      "TV satelital (Direct TV, Antina y otros)",
      "Gas Natural (Naturgy)",
      "Energía Eléctrica (Edenor)",
      "Planta de tratamiento de residuos cloacales",
      "Agua corriente (cooperativa de agua del Pueblo)",
    ],
    lotes: "Desde 900 a 1200 m2.",
  },
  {
    location_id: 25967,
    location_name: "TERRAVISTA",
    nombre: "Terravista",
    ubicacion: "",
    acceso: "",
    caracteristicas_generales:
      "Lotes de 1100 m2 promedio, con distintas tipologías y precios.",
    infraestructura_deportiva: [
      "3 canchas de Fútbol 11",
      "9 canchas de Tenis",
      "Cancha de Hockey",
      "Playón Polideportivo para Voley, Basket y Rollers",
      "3 piscinas",
      "Vestuarios",
      "Sala de Musculación",
    ],
    infraestructura_servicios: [
      "Club House Principal con SPA",
      "Club House Deportivo",
      "Colegio Bartolomé Migre Day School con acceso directo desde el barrio",
      "Seguridad nocturna",
      "Gas Natural",
      "Internet",
      "Electricidad",
      "Pavimento",
      "Teléfono",
      "Cable",
    ],
    lotes: "1100 m2 promedio.",
  },
  {
    location_id: 52060,
    location_name: "WESTON",
    nombre: "Weston",
    ubicacion: "Moreno, Acceso Oeste, km 41, salida Reja Grande.",
    acceso:
      "A 35 minutos de Capital Federal y a 15 minutos de la autopista General Paz.",
    caracteristicas_generales:
      "147 lotes de 730m2 promedio. Tierras altas de frondosa arboleda. Más de 50 familias viviendo.",
    infraestructura_deportiva: [
      "Canchas de tenis",
      "Playón polideportivo",
      "Vestuarios",
      "Gimnasio",
    ],
    infraestructura_servicios: [
      "Seguridad y accesos controlados",
      "Espacios verdes, aire puro y agua natural",
      "Spa cinco estrellas incluido en las expensas",
      "Altos estándares de calidad en su construcción",
      "Piscina indoor climatizada y sauna",
      "Última tecnología en seguridad perimetral",
      "Red de servicios subterráneos de agua natural corriente, gas natural, electricidad y planta de tratamientos de líquidos cloacales",
      "Iluminación pública",
    ],
    lotes: "730m² promedio.",
  },
  {
    location_id: 26237,
    location_name: "HARAS MARIA EUGENIA",
    nombre: "Haras Maria Eugenia",
    ubicacion:
      "Moreno, Paso del Rey, Intendente Corvalan al 2400. A metros del puente de acceso Graham Bell, Acceso Oeste km 38.",
    acceso: "",
    caracteristicas_generales:
      "84 lotes desde 400 metros cuadrados. Cercano a colegios, supermercados y shoppings.",
    infraestructura_deportiva: [
      "Cancha de deportes",
      "Cancha de vóley",
      "Cancha de tenis",
    ],
    infraestructura_servicios: [
      "Agua Corriente",
      "Cloaca",
      "Gas Natural",
      "Internet",
      "Electricidad",
      "Pavimento",
      "Teléfono",
      "Cable",
      "Centro de deportes",
      "Gimnasio",
      "Parrilla",
      "SUM",
      "Pileta",
      "Seguridad 24Hs",
    ],
    lotes: "Desde 400 metros cuadrados.",
  },
  {
    location_id: 25143,
    location_name: "BOCA RATON",
  },
  {
    location_id: 26242,
    location_name: "SANTA ANA",
    nombre: "Santa Ana",
    ubicacion:
      "A 40 minutos del centro de Capital Federal, a 6 minutos del centro de Moreno y 10 minutos de Pilar. Acceso por Acceso Oeste.",
    acceso: "Acceso Oeste",
    caracteristicas_generales:
      "Rodeado de naturaleza. Todos los servicios para vivir en familia.",
    infraestructura_deportiva: [
      "2 canchas de tenis",
      "Canchas de fútbol",
      "Canchas de vóley",
      "Canchas de hockey",
      "Piscina",
    ],
    infraestructura_servicios: [
      "Club House exclusivo de estilo americano, con confitería, vestuarios y salón de usos múltiples para fiestas y eventos sociales",
      "Vigilancia las 24 hs",
      "Calles interiores asfaltadas",
      "Amplias avenidas perimetrales",
      "Agua corriente y electricidad subterránea",
      "Red cloaca interna y red de gas",
      "Prestigioso colegio bilingüe: Sworn College",
    ],
    lotes: "",
  },
  {
    location_id: 52055,
    location_name: "FINCAS DE ALVAREZ",
    nombre: "Fincas de Alvarez",
    ubicacion: "A 600 metros de la Autopista del Oeste.",
    acceso: "",
    caracteristicas_generales: "Lotes desde 720 m2.",
    infraestructura_deportiva: [""],
    infraestructura_servicios: [
      "House 100% equipado",
      "Seguridad privada",
      "Estacionamiento de cortesía",
      "Seguridad",
      "Iluminación",
      "Nueva señalética",
      "Cerca perimetral",
      "Control de Acceso",
      "Parquizado",
      "Vigilancia",
      "Zona arbolada",
      "Asfalto",
      "Club House",
      "Pileta/Solarium",
      "Todos los servicios subterráneos (Gas, Cloacas, Luz y Cable)",
      "House para eventos totalmente equipado",
      "Agua Corriente",
      "Cloaca",
      "Electricidad",
      "Alumbrado público",
      "Red de desagües pluviales",
      "Instalación eléctrica subterránea",
      "Parrilla",
      "Quincho",
      "Solarium",
      "SUM",
      "Apto mascotas",
      "Piscina",
      "Seguridad 24hs",
      "Seguridad Portería",
    ],
    lotes: "Desde 720 m2.",
  },
];
